spring.application.name=autosuggestion

spring.redis.host=localhost
spring.redis.port=6380

# Redis cache configuration
spring.cache.type=redis
spring.cache.redis.enabled=true
spring.cache.redis.cache-null-values=false

# Configure RedisTemplate
spring.redis.template.default-key=my-default-key
spring.redis.template.default-value=my-default-value
spring.redis.template.key-prefix=autosuggestion-stage

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/autosuggestion

#server.servlet.context-path=/demo
